# See https://github.com/esphome/wake-word-voice-assistants/blob/ceff4c72a403549f158b33e5a0b5a5e15c11e14f/m5stack-atom-echo/m5stack-atom-echo.yaml

esp32:
  board: m5stack-atom
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"

remote_transmitter:
  id: m5stack_atom_ir_transmitter
  pin: GPIO12
  carrier_duty_percent: 50%

# INCLUDE OTHER FILE, ALLOWS USE OF GPIO OR I2C
#i2c:
#  sda: GPIO26
#  scl: GPIO32
#  scan: false
#  frequency: 200kHz
#  id: i2c_grove

light:
  - platform: esp32_rmt_led_strip
    id: led
    name: Light
#    disabled_by_default: true
#    entity_category: config
    pin: GPIO27
    default_transition_length: 0s
    chipset: SK6812
    num_leds: 1
    rgb_order: grb
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 250ms
          update_interval: 250ms
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: Button
    filters:
      - delayed_on: 10ms
    on_multi_click:
    - timing:
        - ON for at least 351ms
      then:
        - script.execute: ${m5stack_atom_button_KeyHeldDown_script}
        - homeassistant.event:
            event: esphome.button_pressed
            data:
              button: m5stack-atom_button
              value: KeyHeldDown
    - timing:
        - ON for at least 351ms
        - OFF for at least 0ms
      then:
        - script.execute: ${m5stack_atom_button_KeyReleased_script}
        - homeassistant.event:
            event: esphome.button_pressed
            data:
              button: m5stack-atom_button
              value: KeyReleased
    - timing:
        - ON for 50ms to 350ms
        - OFF for at least 351ms
      then:
        - script.execute: ${m5stack_atom_button_KeyPressed_script}
        - homeassistant.event:
            event: esphome.button_pressed
            data:
              button: m5stack-atom_button
              value: KeyPressed
    - timing:
        - ON for 50ms to 350ms
        - OFF for 50ms to 350ms
        - ON for 50ms to 350ms
        - OFF for at least 351ms
      then:
        - script.execute: ${m5stack_atom_button_KeyPressed2x_script}
        - homeassistant.event:
            event: esphome.button_pressed
            data:
              button: m5stack-atom_button
              value: KeyPressed2x
    - timing:
        - ON for 50ms to 350ms
        - OFF for 50ms to 350ms
        - ON for 50ms to 350ms
        - OFF for 50ms to 350ms
        - ON for 50ms to 350ms
        - OFF for at least 351ms
      then:
        - script.execute: ${m5stack_atom_button_KeyPressed3x_script}
        - homeassistant.event:
            event: esphome.button_pressed
            data:
              button: m5stack-atom_button
              value: KeyPressed3x
