substitutions:
  name: "mt-esp-yinz-rack-ble-01"
  friendly_name: "Yinz Rack BLE ESP"
  mac_address: ""

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

esp32:
  board: esp-wrover-kit  # actually WT32-ETH01 V1.4, some GPIO mappings wrong
  framework:
    type: esp-idf

ethernet:
 domain: .mousetrap
 type: LAN8720
 mdc_pin: GPIO23
 mdio_pin: GPIO18
 clk_mode: GPIO0_IN
 phy_addr: 1
 power_pin: GPIO16
 use_address: 10.2.2.9

time:
  - platform: sntp
    id: sntp_time
    timezone: "America/New_York"
    servers:
     - 10.2.0.2

# Enable logging
logger:

ota:
  password: !secret ota_password_yinz_rack_ble_01

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key_yinz_rack_ble_01

switch:
  - platform: restart
    name: "Restart ${friendly_name}"
    entity_category: diagnostic

button:
- platform: safe_mode
  name: "Safe Mode Boot ${friendly_name}"
  entity_category: diagnostic

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

# ble_client:
#   - mac_address: !secret mac_address_yinz_rack_ble_01
#     id: par_bar_opal_ice_01
#     on_connect:
#       then:
#         - binary_sensor.template.publish:
#             id: par_bar_opal_ice_01_connected
#             state: ON
#         - lambda: |-
#             ESP_LOGD("ble_client_lambda", "Connected to par_bar_opal_ice_01");
#     on_disconnect:
#       then:
#         - binary_sensor.template.publish:
#             id: par_bar_opal_ice_01_connected
#             state: OFF
#         - lambda: |-
#             ESP_LOGD("ble_client_lambda", "Disconnected from par_bar_opal_ice_01");

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
    ssid:
      name: "${friendly_name} Connected SSID"
    bssid:
      name: "${friendly_name} Connected BSSID"
#   - platform: template
#     id: par_bar_opal_ice_01_state
#     name: "Par Bar Opal Ice Machine State"
# #    icon: 'mdi:battery'

# cover:
#   - platform: template
#     id: par_bar_opal_ice_01_ice_bin
#     name: "Par Bar Opal Ice Machine Ice Bin State"
# #    icon: 'mdi:battery'

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
  # - platform: template
  #   id: par_bar_opal_ice_01_connected
  #   name: "Par Bar Opal Ice Machine Connected"
  # - platform: template
  #   id: par_bar_opal_ice_01_night_light
  #   name: "Par Bar Opal Ice Machine Night Light"

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal Strength"
    update_interval: 60s
  # - platform: ble_client
  #   ble_client_id: par_bar_opal_ice_01
  #   id: par_bar_opal_ice_01_state_raw
  #   service_uuid: "3e6763c5-9429-40cc-909e-bebf8c7487be"
  #   characteristic_uuid: "097a2751-ca0d-432f-87b5-7d2f31e45551"
  #   notify: true
  #   update_interval: 60s
  #   # internal: true
  #   # lambda: |-
  #   #   if (x[0] == 0) {
  #   #     id(par_bar_opal_ice_01_state).publish_state("Making Ice");
  #   #   } else if (x[0] == 1) {
  #   #     id(par_bar_opal_ice_01_state).publish_state("Add Water");
  #   #   } else if (x[0] == 2) {
  #   #     id(par_bar_opal_ice_01_state).publish_state("Idle");
  #   #   } else {
  #   #     id(par_bar_opal_ice_01_state).publish_state("Off");
  #   #   }
  #   #   return *((float*)(&x[0]));
  # - platform: ble_client
  #   ble_client_id: par_bar_opal_ice_01
  #   id: par_bar_opal_ice_01_ice_bin_raw
  #   service_uuid: "3e6763c5-9429-40cc-909e-bebf8c7487be"
  #   characteristic_uuid: "5bcbf6b1-de80-94b6-0f4b-99fb984707b6"
  #   notify: true
  #   update_interval: 60s
  #   # internal: true
  #   # lambda: |-
  #   #   if (x[0] == 1) {
  #   #     id(par_bar_opal_ice_01_ice_bin).position = COVER_OPEN;
  #   #   } else {
  #   #     id(par_bar_opal_ice_01_ice_bin).position = COVER_CLOSED;
  #   #   }
  #   #   id(par_bar_opal_ice_01_ice_bin).publish_state();
  #   #   return *((float*)(&x[0]));
  # - platform: ble_client
  #   ble_client_id: par_bar_opal_ice_01
  #   id: par_bar_opal_ice_01_night_light_raw
  #   service_uuid: "3e6763c5-9429-40cc-909e-bebf8c7487be"
  #   characteristic_uuid: "37988f00-ea39-4a2d-9983-afad6535c02e"
  #   notify: true
  #   update_interval: 60s
  #   # internal: true
  #   # lambda: |-
  #   #   if (x[0] == 0) {
  #   #     id(par_bar_opal_ice_01_night_light).publish_state(true);
  #   #   } else {
  #   #     id(par_bar_opal_ice_01_night_light).publish_state(false);
  #   #   }
  #   #   return *((float*)(&x[0]));

# output:
#   - platform: ble_client
#     id: par_bar_opal_ice_01_make_ice
#     ble_client_id: par_bar_opal_ice_01
#     service_uuid: "3e6763c5-9429-40cc-909e-bebf8c7487be"
#     characteristic_uuid: "79994230-4b04-40cd-85c9-02dd1a8d4dd0"
#     require_response: false
