substitutions:
  name: "mt-esp-laundry-room-01"
  friendly_name: "Laundry Room ESP"
  mac_address: !secret mac_address_laundry_room_01

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

esp32:
  board: m5stack-atom
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key_laundry_room_01

ota:
  password: !secret ota_password_laundry_room_01

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  domain: !secret wifi_domain

time:
  - platform: sntp
    id: sntp_time
    timezone: "America/New_York"
    servers:
     - 10.2.0.2

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: ${friendly_name} Button

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
    ssid:
      name: "${friendly_name} Connected SSID"
    bssid:
      name: "${friendly_name} Connected BSSID"

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal Strength"
    update_interval: 60s

switch:
  - platform: restart
    name: "Restart ${friendly_name}"

button:
- platform: safe_mode
  name: "Safe Mode Boot ${friendly_name}"
  entity_category: diagnostic

light:
  - platform: neopixelbus
    name: ${friendly_name} Light
    pin: GPIO27
    variant: SK6812
    num_leds: 1
    type: GRB

media_player:
  - platform: i2s_audio
    id: media_out
    name: ${friendly_name} Speaker
    dac_type: external
    i2s_lrclk_pin: GPIO33
    i2s_dout_pin: GPIO22
    i2s_bclk_pin: GPIO19
    mode: mono

remote_transmitter:
  id: desk_hdmi_switch_ir_transmitter
  pin: GPIO12
  carrier_duty_percent: 50%
