substitutions:
  name: "mt-esp-disco-01"
  friendly_name: "Disco ESP"
  mac_address: !secret mac_address_disco_01
  ip_address: "10.2.2.60" # for use_address name changes

packages:
  common: !include ./common/common.yaml
  net_wifi: !include ./common/net_wifi.yaml
  # net_ethernet: !include ./common/net_ethernet.yaml

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

esp8266:
  board: nodemcuv2

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key_disco_01

ota:
  - platform: esphome
    password: !secret ota_password_disco_01

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO10
      inverted: false
    name: "DiscoSwitch"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

light:
  - platform: status_led
    name: "Status LED"
    pin: 
      number: GPIO2
      inverted: true
