wifi:
  use_address: "${ip_address}"
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  domain: !secret wifi_domain

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"
    bssid:
      name: "Connected BSSID"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 60s
